# Generated by Django 4.2 on 2023-09-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_order_date_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
