# Generated by Django 4.2 on 2023-09-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_zipcode_order_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
